languaje: node_js
cache:
  directories:
    - ~!@/.nmp
node_js:
  -'9'
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: master
  commit_message: "Deply release ${TRAVIS_TAG}"
  on:
    branch: develop